### ISSUE TITLE
Beta 1 Testing checklist

### ISSUE THREAD

**Issue by cwRichardKim** [jumbosmash/jumbosmash-rn#118]
**Pre-signup**
- [x] User signs up from scratch, reaches presignup page
- [x] Incomplete signup goes to account creation page
- [x] User changed to beta tester, asked to logout and log back in again, user is able to pass presignup page
- [x] Signin allows user to pass
- [x] User tries to change date, sees cheater page

**Active**
- [x] User signs up from scratch, goes to app
- [x] Incomplete user signup gets account creation page
- [x] Login goes to app page
 - [x] Disabled user can't log in

**Post-signup**
- [x] dummy works from scratch, no login required
- [x] logged in user can still use app
- [x] user can log in by "keep smashing"
- [x] user can sign up by "keep smashing"
